# Generated by Django 6.0.2 on 2026-03-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_coachingsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='avatar_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='price',
            field=models.IntegerField(default=0, help_text='Price per session in dollars'),
        ),
        migrations.AddField(
            model_name='coach',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='coach',
            name='specialty',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='coach',
            name='tags',
            field=models.JSONField(default=list),
        ),
    ]
