# Generated by Django 6.0.2 on 2026-04-04 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_member_goals_restrictions'),
        ('users', '0008_coach_is_active_coach_rejection_reason_coach_status'),
    ]

    operations = [
    ]
