# Generated by Django 6.0.2 on 2026-04-07 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_dietaryrestriction_memberdietaryrestriction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='member',
            name='restrictions',
        ),
    ]
