# Generated by Django 6.0.2 on 2026-04-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_member_goals_remove_member_restrictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='avatar_b64',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not', 'Prefer not to say')], default='', max_length=20),
        ),
    ]
