# Generated by Django 6.0.2 on 2026-03-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachingsession',
            name='duration',
            field=models.IntegerField(default=60, help_text='Duration in minutes'),
        ),
        migrations.AlterField(
            model_name='coachingsession',
            name='goals',
            field=models.TextField(blank=True),
        ),
    ]
