# Generated by Django 6.0.2 on 2026-04-07 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0004_equipmentreservation'),
        ('coaching', '0005_delete_gymrule'),
    ]

    operations = [
    ]
