# Generated by Django 6.0.2 on 2026-03-24 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationPolicy',
            fields=[
                ('policy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gym.policy')),
                ('penalty_type', models.CharField(choices=[('fixed', 'Fixed fee'), ('percentage', 'Percentage of session price'), ('none', 'No penalty')], default='none', max_length=20)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('notice_hours', models.PositiveIntegerField(default=24, help_text='Hours of notice required to avoid penalty')),
            ],
            options={
                'db_table': 'cancellation_policies',
            },
            bases=('gym.policy',),
        ),
        migrations.AlterModelOptions(
            name='policy',
            options={'ordering': ['category__name', 'title']},
        ),
        migrations.CreateModel(
            name='PolicyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_categories', to='gym.gym')),
            ],
            options={
                'verbose_name_plural': 'policy categories',
                'db_table': 'policy_categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='policy',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='gym.policycategory'),
        ),
    ]
