# Generated by Django 6.0.2 on 2026-03-24 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_cancellationpolicy_alter_policy_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipment',
        ),
    ]
