# Generated by Django 6.0.2 on 2026-04-03 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_delete_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='current_occupancy',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gym',
            name='max_capacity',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
