# Generated by Django 6.0.2 on 2026-03-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutexercise',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
