# Generated by Django 6.0.2 on 2026-03-22 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_coach_avatar_url_coach_price_coach_rating_and_more'),
        ('workouts', '0002_alter_workoutexercise_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to='users.coach'),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to='users.member'),
        ),
    ]
