# Generated by Django 6.0.2 on 2026-03-24 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_goals', '0001_initial'),
        ('users', '0006_coach_avatar_url_coach_price_coach_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessgoal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_goals', to='users.member'),
        ),
    ]
